#!/bin/bash
# brainbuddy installer. wraps an existing statusline, never replaces it.
set -euo pipefail

usage() {
  cat <<'EOF'
brainbuddy installer

  ./install.sh                     install and wire up the statusline
  ./install.sh --folder <path>     count a folder of markdown notes
  ./install.sh --vault <path>      use a structured vault layout
  ./install.sh --statusline <cmd>  wrap this command instead of settings.json's
  ./install.sh --inline            one-line segment instead of the boxed column
  ./install.sh --no-wire           install the library only, wire it yourself
  ./install.sh --uninstall         unwire and restore your old statusline
EOF
}

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOMEDIR="$HOME/.claude/brainbuddy"
LIB="$HOMEDIR/lib"
CMDS="$HOME/.claude/commands"
SETTINGS="$HOME/.claude/settings.json"
SHIM="$HOMEDIR/statusline-brainbuddy.sh"
WRAPPED="$HOMEDIR/wrapped-command"
BEGIN="# >>> brainbuddy >>>"
END="# <<< brainbuddy <<<"
COMMAND_NAMES="brainbuddy brainbuddy-hide brainbuddy-show brainbuddy-new brainbuddy-hatch"
VAULT=""
FOLDER=""
WIRE=1
INLINE=0
MODE=install
STATUSLINE=""

while [ $# -gt 0 ]; do
  case "$1" in
    --vault) VAULT="${2:-}"; shift 2 ;;
    --folder) FOLDER="${2:-}"; shift 2 ;;
    --statusline) STATUSLINE="${2:-}"; shift 2 ;;
    --inline) INLINE=1; shift ;;
    --no-wire) WIRE=0; shift ;;
    --uninstall) MODE=uninstall; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1"; exit 1 ;;
  esac
done

command -v python3 >/dev/null 2>&1 || { echo "python3 not found. brainbuddy needs it."; exit 1; }

read_statusline() {
  python3 - "$SETTINGS" <<'PY'
import json, sys
try:
    with open(sys.argv[1]) as f:
        print((json.load(f).get("statusLine") or {}).get("command", ""))
except Exception:
    print("")
PY
}

write_statusline() {
  # $1 = command, or empty to drop the key entirely
  python3 - "$SETTINGS" "$1" <<'PY'
import json, os, shutil, sys
path, command = sys.argv[1], sys.argv[2]
data = {}
if os.path.exists(path):
    # raw bytes, before parsing. a backup of the parse result is worthless
    # exactly when you need it
    backup = path + ".pre-brainbuddy.bak"
    if not os.path.exists(backup):
        shutil.copyfile(path, backup)
    with open(path) as f:
        try:
            data = json.load(f)
        except ValueError:
            sys.stderr.write("settings.json isn't valid JSON, so nothing was changed. fix it and re-run.\n")
            raise SystemExit(1)
# mutate the existing entry rather than replacing it, or siblings like padding
# get dropped on the way through
line = data.get("statusLine")
if not isinstance(line, dict):
    line = {}
if command:
    line.setdefault("type", "command")
    line["command"] = command
    data["statusLine"] = line
else:
    data.pop("statusLine", None)
os.makedirs(os.path.dirname(path), exist_ok=True)
with open(path, "w") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
PY
}

# A command can be `bash ~/foo.sh`, so the file might be the whole string or its
# first word. Echoes the first one that's a real file, or nothing.
target_path_of() {
  local cmd="$1" cand
  for cand in "$cmd" "$(eval echo "${cmd%% *}" 2>/dev/null || true)"; do
    if [ -n "$cand" ] && [ -f "$cand" ]; then echo "$cand"; return 0; fi
  done
  echo ""
}

# none | ours | modified. a block we generated has to come out or the creature
# renders twice, but one that's been edited is their code, so we leave it.
classify_target() {
  local target="$1"
  if [ -z "$target" ] || [ ! -f "$target" ]; then echo none; return 0; fi
  python3 - "$target" "$BEGIN" "$END" <<'PY'
import sys
path, begin, end = sys.argv[1], sys.argv[2], sys.argv[3]
GENERATED = ['printf " "', '"$HOME/.claude/brainbuddy/statusline-brainbuddy.sh"']
try:
    with open(path) as f:
        lines = [line.rstrip("\n") for line in f]
except OSError:
    print("none")
    raise SystemExit
inner, inside, fenced = [], False, False
for line in lines:
    s = line.strip()
    if s == begin:
        inside, fenced = True, True
        continue
    if s == end:
        inside = False
        continue
    if inside and s:
        inner.append(s)
if fenced:
    print("ours" if inner == GENERATED else "modified")
elif any("brainbuddy.cli" in line for line in lines):
    print("modified")
else:
    print("none")
PY
}

# bash -c not sh -c, since the wrapped string is whatever was in
# statusLine.command and may lean on bash, which isn't sh everywhere.
write_shim() {
  if [ "$INLINE" = 1 ]; then
    cat > "$SHIM" <<'EOF'
#!/bin/bash
# generated by the brainbuddy installer. safe to delete, reinstalling restores it.
# inline mode: your statusline, then the creature as a one-line segment after it.
INPUT="$(cat)"
LEFT=""
if [ -s "$HOME/.claude/brainbuddy/wrapped-command" ]; then
  LEFT="$(printf '%s' "$INPUT" | bash -c "$(cat "$HOME/.claude/brainbuddy/wrapped-command")" 2>/dev/null)" || LEFT=""
fi
printf '%s' "$LEFT"
if [ -n "$LEFT" ]; then printf ' '; fi
PYTHONPATH="$HOME/.claude/brainbuddy/lib" python3 -m brainbuddy.cli render 2>/dev/null || true
EOF
  else
    cat > "$SHIM" <<'EOF'
#!/bin/bash
# generated by the brainbuddy installer. safe to delete, reinstalling restores it.
# your statusline, with the creature as a fixed-width column to the left of it.
INPUT="$(cat)"
LEFT=""
if [ -s "$HOME/.claude/brainbuddy/wrapped-command" ]; then
  LEFT="$(printf '%s' "$INPUT" | bash -c "$(cat "$HOME/.claude/brainbuddy/wrapped-command")" 2>/dev/null)" || LEFT=""
fi
PYTHONPATH="$HOME/.claude/brainbuddy/lib" python3 -m brainbuddy.cli compose "$LEFT" 2>/dev/null || printf '%s' "$LEFT"
EOF
  fi
  chmod +x "$SHIM"
}

strip_legacy_block() {
  local target="$1"
  python3 - "$target" "$BEGIN" "$END" <<'PY'
import sys
path, begin, end = sys.argv[1], sys.argv[2], sys.argv[3]
with open(path) as f:
    lines = f.readlines()
out, skip = [], False
for line in lines:
    if line.strip() == begin: skip = True; continue
    if line.strip() == end: skip = False; continue
    if not skip: out.append(line)
with open(path, "w") as f:
    f.writelines(out)
PY
  echo "  removed the old brainbuddy block from $(basename "$target")"
}

if [ "$MODE" = uninstall ]; then
  PREVIOUS=""
  # `[ test ] && assign` is the whole statement here, so a false test would trip set -e
  if [ -s "$WRAPPED" ]; then PREVIOUS="$(cat "$WRAPPED")"; fi
  CURRENT="$(read_statusline)"
  if [ "$CURRENT" = "$SHIM" ]; then
    write_statusline "$PREVIOUS"
    if [ -n "$PREVIOUS" ]; then
      echo "restored your previous statusline"
    else
      echo "removed the statusline entry we added"
    fi
  fi
  LEGACY="$(target_path_of "$CURRENT")"
  case "$(classify_target "$LEGACY")" in
    ours) strip_legacy_block "$LEGACY" ;;
    modified) echo "left $(basename "$LEGACY") alone, you've edited the brainbuddy block in it" ;;
  esac
  rm -rf "$LIB" "$SHIM" "$WRAPPED"
  for cmd in $COMMAND_NAMES; do rm -f "$CMDS/$cmd.md"; done
  echo "uninstalled. state kept at ~/.claude/brainbuddy/state.json (delete it yourself for a clean slate)"
  exit 0
fi

echo "installing brainbuddy"
mkdir -p "$LIB" "$CMDS" "$HOMEDIR"
rm -rf "$LIB/brainbuddy"
cp -R "$SRC/brainbuddy" "$LIB/brainbuddy"
for cmd in $COMMAND_NAMES; do
  if [ -f "$SRC/commands/$cmd.md" ]; then cp "$SRC/commands/$cmd.md" "$CMDS/$cmd.md"; fi
done
echo "  library  -> $LIB"
echo "  commands -> $CMDS  (/brainbuddy, -new, -hatch, -hide, -show)"

# always, even under --no-wire: self-wirers point their own script at it
write_shim

bb() { PYTHONPATH="$LIB" python3 -m brainbuddy.cli "$@"; }

if [ -n "$FOLDER" ]; then
  bb config provider folder >/dev/null
  bb config vault_root "$FOLDER" >/dev/null
  echo "  provider -> folder of notes at $FOLDER"
elif [ -n "$VAULT" ]; then
  bb config provider vault >/dev/null
  bb config vault_root "$VAULT" >/dev/null
  echo "  provider -> vault at $VAULT"
else
  # report what's actually configured. this used to claim stock memory on every
  # run without --vault, including reinstalls over a vault setup it left alone
  CURRENT_PROVIDER=$(bb config 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('provider','claude'), d.get('vault_root') or '')" 2>/dev/null || echo "claude ")
  case "$CURRENT_PROVIDER" in
    "vault "*) echo "  provider -> vault at ${CURRENT_PROVIDER#vault }  (unchanged)" ;;
    "folder "*) echo "  provider -> folder of notes at ${CURRENT_PROVIDER#folder }  (unchanged)" ;;
    *) echo "  provider -> stock Claude Code memory (~/.claude/projects/*/memory)" ;;
  esac
fi

if [ "$WIRE" = 1 ]; then
  if [ -n "$STATUSLINE" ]; then
    EXISTING="$STATUSLINE"
  else
    EXISTING="$(read_statusline)"
  fi

  # re-installing over ourselves, so keep what we wrapped last time
  # rather than the shim we're pointing at
  if [ "$EXISTING" = "$SHIM" ]; then
    EXISTING=""
    if [ -s "$WRAPPED" ]; then EXISTING="$(cat "$WRAPPED")"; fi
  fi

  # Our own unmodified block comes out, since wrapping as well would draw two
  # creatures. A block someone has edited is theirs, so we stop instead.
  HANDWIRED=""
  TARGET="$(target_path_of "$EXISTING")"
  case "$(classify_target "$TARGET")" in
    ours) strip_legacy_block "$TARGET" ;;
    modified) HANDWIRED="$TARGET" ;;
  esac
fi

if [ "$WIRE" = 1 ] && [ -n "${HANDWIRED:-}" ]; then
  echo "  ! $(basename "$HANDWIRED") calls brainbuddy itself, so wrapping it would draw two creatures"
  echo "    leaving your wiring and settings.json alone, library updated in place."
  echo "    to hand the wiring over, drop the brainbuddy lines from that script and re-run"
  WIRE=0
fi

if [ "$WIRE" = 1 ]; then
  if [ -n "$EXISTING" ]; then
    printf '%s' "$EXISTING" > "$WRAPPED"
    WIRED="  statusline -> wrapping your existing one, creature on the left"
  else
    : > "$WRAPPED"
    WIRED="  statusline -> set in settings.json"
  fi

  # after the write, not before, so a refusal doesn't get announced as a success
  write_statusline "$SHIM"
  echo "$WIRED"
fi

echo
# lay the first egg so the zero state is an egg rather than nothing at all.
# `new` exits 1 when a buddy exists, which is the re-install path: leave it be
if bb new >/dev/null 2>&1; then
  echo "an egg is waiting in your statusline. open it:"
  echo "  /brainbuddy-hatch"
  echo "it hatches at whatever level your memory has already earned."
else
  bb list
fi

# XP comes from a memory system. If there isn't one, say so here rather than
# leaving a level-0 egg and no explanation.
SOURCE_HELP="$(bb sources 2>/dev/null || true)"
case "$SOURCE_HELP" in
  counting*) ;;
  "") ;;
  *) echo; echo "$SOURCE_HELP" ;;
esac
