#!/bin/bash
# brainbuddy installer. composes with an existing statusline, never replaces it.
set -euo pipefail

usage() {
  cat <<'EOF'
brainbuddy installer

  ./install.sh                     install and wire up the statusline
  ./install.sh --vault <path>      use a vault layout instead of stock Claude Code memory
  ./install.sh --statusline <path> wire into a specific script (project-level setups)
  ./install.sh --no-wire           install the library only, wire it yourself
  ./install.sh --uninstall         remove the wiring and restore backups
EOF
}

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB="$HOME/.claude/brainbuddy/lib"
CMDS="$HOME/.claude/commands"
SETTINGS="$HOME/.claude/settings.json"
SHIM="$HOME/.claude/brainbuddy/statusline-brainbuddy.sh"
BEGIN="# >>> brainbuddy >>>"
END="# <<< brainbuddy <<<"
VAULT=""
WIRE=1
MODE=install
STATUSLINE=""

while [ $# -gt 0 ]; do
  case "$1" in
    --vault) VAULT="${2:-}"; shift 2 ;;
    --statusline) STATUSLINE="${2:-}"; shift 2 ;;
    --no-wire) WIRE=0; shift ;;
    --uninstall) MODE=uninstall; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1"; exit 1 ;;
  esac
done

command -v python3 >/dev/null 2>&1 || { echo "python3 not found. brainbuddy needs it."; exit 1; }

resolve_statusline() {
  python3 - "$SETTINGS" <<'PY'
import json, sys
try:
    with open(sys.argv[1]) as f:
        print((json.load(f).get("statusLine") or {}).get("command", ""))
except Exception:
    print("")
PY
}

if [ "$MODE" = uninstall ]; then
  if [ -n "$STATUSLINE" ]; then
    TARGET="$STATUSLINE"
  else
    EXISTING="$(resolve_statusline)"
    TARGET="${EXISTING%% *}"
  fi
  # Strip our block out of a script we appended to, rather than restoring a
  # backup wholesale. The user may have edited the rest of the file since.
  if [ -n "$TARGET" ] && [ -f "$TARGET" ] && grep -q "$BEGIN" "$TARGET" 2>/dev/null; then
    python3 - "$TARGET" "$BEGIN" "$END" <<'PY'
import sys
path, begin, end = sys.argv[1], sys.argv[2], sys.argv[3]
with open(path) as f:
    lines = f.readlines()
out, skip = [], False
for line in lines:
    if line.strip() == begin: skip = True; continue
    if line.strip() == end: skip = False; continue
    if not skip: out.append(line)
with open(path, "w") as f:
    f.writelines(out)
PY
    echo "removed the brainbuddy block from your statusline"
  fi
  rm -rf "$LIB" "$SHIM" "$CMDS/brainbuddy.md"
  echo "uninstalled. state kept at ~/.claude/brainbuddy/state.json (delete it yourself if you want a clean slate)"
  exit 0
fi

echo "installing brainbuddy"
mkdir -p "$LIB" "$CMDS" "$HOME/.claude/brainbuddy"
rm -rf "$LIB/brainbuddy"
cp -R "$SRC/brainbuddy" "$LIB/brainbuddy"
for cmd in brainbuddy brainbuddy-hide brainbuddy-show brainbuddy-new brainbuddy-hatch; do
  [ -f "$SRC/commands/$cmd.md" ] && cp "$SRC/commands/$cmd.md" "$CMDS/$cmd.md"
done
echo "  library  -> $LIB"
echo "  commands -> $CMDS  (/brainbuddy, -new, -hatch, -hide, -show)"

cat > "$SHIM" <<'EOF'
#!/bin/bash
# generated by the brainbuddy installer. safe to delete, reinstalling restores it.
PYTHONPATH="$HOME/.claude/brainbuddy/lib" python3 -m brainbuddy.cli render 2>/dev/null || true
EOF
chmod +x "$SHIM"

bb() { PYTHONPATH="$LIB" python3 -m brainbuddy.cli "$@"; }

if [ -n "$VAULT" ]; then
  bb config provider vault >/dev/null
  bb config vault_root "$VAULT" >/dev/null
  echo "  provider -> vault at $VAULT"
else
  # report what's actually configured. this used to claim stock memory on every
  # run without --vault, including reinstalls over a vault setup it left alone
  CURRENT_PROVIDER=$(bb config 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('provider','claude'), d.get('vault_root') or '')" 2>/dev/null || echo "claude ")
  case "$CURRENT_PROVIDER" in
    "vault "*) echo "  provider -> vault at ${CURRENT_PROVIDER#vault }  (unchanged)" ;;
    *) echo "  provider -> stock Claude Code memory (~/.claude/projects/*/memory)" ;;
  esac
fi

if [ "$WIRE" = 1 ]; then
  if [ -n "$STATUSLINE" ]; then
    EXISTING="$STATUSLINE"; TARGET="$STATUSLINE"
  else
    EXISTING="$(resolve_statusline)"; TARGET="${EXISTING%% *}"
  fi
  if [ "$TARGET" = "$SHIM" ]; then
    # already the statusline. appending here would make the shim call itself
    echo "  statusline already points at brainbuddy, nothing to wire"
  elif [ -n "$TARGET" ] && [ -f "$TARGET" ] && head -1 "$TARGET" | grep -q '^#!'; then
    if grep -q "$BEGIN" "$TARGET" 2>/dev/null; then
      echo "  statusline already wired, leaving it alone"
    else
      cp "$TARGET" "$TARGET.pre-brainbuddy.bak"
      # $HOME rather than the expanded path, since statusline scripts get committed
      printf '\n%s\nprintf " "\n%s\n%s\n' "$BEGIN" '"$HOME/.claude/brainbuddy/statusline-brainbuddy.sh"' "$END" >> "$TARGET"
      echo "  statusline -> appended to $(basename "$TARGET") (backup: $(basename "$TARGET").pre-brainbuddy.bak)"
    fi
  elif [ -n "$EXISTING" ]; then
    echo "  ! your statusline is a plain command, not a script:"
    echo "      $EXISTING"
    echo "    add this after it yourself, or point statusLine.command at a script:"
    echo "      $SHIM"
  else
    python3 - "$SETTINGS" "$SHIM" <<'PY'
import json, os, sys
path, shim = sys.argv[1], sys.argv[2]
data = {}
if os.path.exists(path):
    with open(path) as f:
        try: data = json.load(f)
        except ValueError: data = {}
    os.replace(path, path + ".pre-brainbuddy.bak")
data["statusLine"] = {"type": "command", "command": shim}
os.makedirs(os.path.dirname(path), exist_ok=True)
with open(path, "w") as f:
    json.dump(data, f, indent=2)
PY
    echo "  statusline -> set in settings.json"
  fi
fi

echo
# lay the first egg so the zero state is an egg rather than nothing at all.
# `new` exits 1 when a buddy exists, which is the re-install path: leave it be
if bb new >/dev/null 2>&1; then
  echo "an egg is waiting in your statusline. open it:"
  echo "  /brainbuddy-hatch"
  echo "it hatches at whatever level your memory has already earned."
else
  bb list
fi
