"""Card plugins for hosts that load JS instead of reading a hook config.

opencode and Amp have no shell-hook setting. Each loads JS modules from a
plugin directory, so the card for those two is a generated file that runs
`hookcard --host <host>` when a turn ends and shows the line the cli prints.
The templates are Python strings; the binary goes in the way snippets
resolves it, spelled with $HOME so no absolute home path lands in the file.
"""

import json
import os
import shutil

from . import snippets

PLUGIN_HOSTS = ("opencode", "amp")

# the first line of every file we write. unwire only removes files carrying it
MARKER = "generated by terminalcreature"
HEADER = "// %s. safe to delete, reinstalling restores it.\n" % MARKER

# how long a handler may wait on the cli before giving up on this turn
TIMEOUT_MS = 5000

# dir: the host's config dir, its presence is "installed", and detect says so
# for the hosts table. file: our plugin, relative to dir. owned: a directory
# under dir that is entirely ours, removed on unwire when empty. runtimes: any
# one of these on PATH runs the plugin.
REGISTRY = {
    "opencode": {
        "label": "opencode", "dir": "~/.config/opencode", "detect": "~/.config/opencode",
        "file": "plugins/terminalcreature.js", "owned": None,
        "runtimes": ("bun", "node"),
    },
    "amp": {
        "label": "Amp", "dir": "~/.config/amp", "detect": "~/.config/amp",
        "file": "plugins/terminalcreature/index.js", "owned": "plugins/terminalcreature",
        "runtimes": ("bun",),
    },
}

# opencode: a module exporting plugin functions, each given the sdk client and
# bun's $ shell and returning hooks. the event hook sees every server event;
# session.idle carries the session id. the toast goes through the sdk client.
OPENCODE_TEMPLATE = HEADER + """\
// shows your creature's card as a toast when a turn ends.

const COMMAND = __COMMAND__;
const TIMEOUT_MS = __TIMEOUT__;

export const TerminalCreature = async ({ client, $ }) => {
  return {
    event: async ({ event }) => {
      if (!event || event.type !== "session.idle") return;
      try {
        const props = event.properties || {};
        const payload = JSON.stringify({ session_id: props.sessionID || "" });
        // sh expands $HOME in COMMAND; the payload rides in on stdin
        const run = $`sh -c ${COMMAND} < ${new Response(payload)}`.quiet().nothrow().text();
        const quiet = new Promise((resolve) => setTimeout(() => resolve(""), TIMEOUT_MS));
        const line = String((await Promise.race([run, quiet])) || "").trim();
        if (!line) return;
        await client.tui.showToast({ body: { message: line, variant: "info" } });
      } catch (e) {
        // the creature never takes the host down with it
      }
    },
  };
};
"""

# amp: a directory plugin is <name>/index.js exporting a default function that
# gets the PluginAPI. agent.end fires per turn with the thread id; ctx.ui.notify
# shows a line in the tui and web. plugins run under bun, so Bun.spawn is here.
AMP_TEMPLATE = HEADER + """\
// shows your creature's card as a notification when a turn ends.

export const description = "Shows your terminalcreature after each turn.";

const COMMAND = __COMMAND__;
const TIMEOUT_MS = __TIMEOUT__;

export default function (amp) {
  amp.on("agent.end", async (event, ctx) => {
    try {
      // events arrive for every thread this client hosts; only the one on screen gets a card
      const active = amp.activeThread && amp.activeThread.current;
      const thread = (event && event.thread && event.thread.id) || "";
      if (active && thread && active.id !== thread) return;
      const payload = new TextEncoder().encode(JSON.stringify({ session_id: thread }));
      // sh expands $HOME in COMMAND; the payload rides in on stdin
      const proc = Bun.spawn(["sh", "-c", COMMAND], {
        stdin: payload, stdout: "pipe", stderr: "ignore", timeout: TIMEOUT_MS,
      });
      const line = (await new Response(proc.stdout).text()).trim();
      if (!line) return;
      await ctx.ui.notify(line);
    } catch (e) {
      // the creature never takes the host down with it
    }
  });
}
"""

TEMPLATES = {"opencode": OPENCODE_TEMPLATE, "amp": AMP_TEMPLATE}


def _home_form(shell):
    """~/x as $HOME/x. sh -c expands it, and the file never carries a real home."""
    if shell.startswith("~/"):
        return "$HOME" + shell[1:]
    return shell


def render(host, binary=None):
    """The plugin file for host, as text."""
    shell = _home_form(binary or snippets.resolve_binary()["shell"])
    command = "%s hookcard --host %s" % (shell, host)
    return (TEMPLATES[host]
            .replace("__COMMAND__", json.dumps(command))
            .replace("__TIMEOUT__", str(TIMEOUT_MS)))


def host_dir(host):
    return os.path.expanduser(REGISTRY[host]["dir"])


def plugin_path(host):
    return os.path.join(host_dir(host), REGISTRY[host]["file"])


def installed(host):
    return os.path.isdir(host_dir(host))


def _read(path):
    try:
        with open(path, "r") as f:
            return f.read()
    except OSError:
        return None


def _is_ours(text):
    return text is not None and text.startswith(HEADER)


def _atomic_write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp-terminalcreature"
    with open(tmp, "w") as f:
        f.write(text)
    os.replace(tmp, path)


def missing_runtime(host):
    """"runtime bun not found" style note, or "" when one of the runtimes is on PATH."""
    runtimes = REGISTRY[host]["runtimes"]
    if any(shutil.which(r) for r in runtimes):
        return ""
    return "runtime %s not found" % " or ".join(runtimes)


def wire_plugin(host, binary=None):
    """Write the plugin file, creating dirs. Rewriting the same text is a no-op,
    and a file at our path that isn't ours is left alone. One-line message.
    """
    spec = REGISTRY[host]
    path = plugin_path(host)
    text = render(host, binary)
    current = _read(path)
    if current == text:
        message = "already wired, %s" % spec["file"]
    elif current is not None and not _is_ours(current):
        message = "%s exists and isn't ours, left it alone" % spec["file"]
    else:
        _atomic_write(path, text)
        message = ("updated %s" if current is not None else "wrote %s") % spec["file"]
    note = missing_runtime(host)
    return message + (" (%s)" % note if note else "")


def unwire_plugin(host):
    """Remove our file, and our directory once it's empty. Nothing else."""
    spec = REGISTRY[host]
    path = plugin_path(host)
    if not _is_ours(_read(path)):
        return "wasn't wired"
    os.remove(path)
    if spec["owned"]:
        try:
            os.rmdir(os.path.join(host_dir(host), spec["owned"]))
        except OSError:
            pass
    return "removed %s" % spec["file"]


def plugin_status(host):
    """not installed | wired | not wired"""
    if not installed(host):
        return "not installed"
    return "wired" if _is_ours(_read(plugin_path(host))) else "not wired"


def doctor_lines():
    """One line per plugin host, shaped like the statusline hosts block."""
    lines = []
    for host in PLUGIN_HOSTS:
        status = plugin_status(host)
        if status != "not installed":
            status = "card, " + status
            note = missing_runtime(host)
            if note:
                status += " (%s)" % note
        lines.append("  %-8s %-19s %s" % (host, REGISTRY[host]["label"], status))
    return lines
